export const CountryData = [
    {
      "Capital": "Abuja",
      "Largest city": "Lagos",
      "Official languages": "English",
      "National languages": "Hausa Igbo Yoruba",
      "Regional languages[2]": "Over 525 languages",
      "Ethnic groups": "30% Hausa",
      "Government": "Federal presidential constitutional republic",
      "Legislature": "National Assembly",
      "Gini": "35.1",
      "HDI": "0.535",
      "Currency": "Naira",
      "Time zone": "UTC+01:00",
      "Driving side": "right",
      "Calling code": "+234",
      "Name": "nigeria"
    },
    {
      "Capital": "Washington, D.C.",
      "Largest city": "New York City",
      "Official languages": "None at the federal level",
      "National language": "English",
      "Ethnic groups": "By race:",
      "Religion": "70% Christianity",
      "Government": "Federal presidential constitutional republic",
      "Legislature": "Congress",
      "Gini": "39.4",
      "HDI": "0.921",
      "Currency": "Dollar",
      "Time zone": "UTC−4 to −12, +10, +11",
      "Date format": "mm/dd/yyyy",
      "Driving side": "right",
      "Calling code": "+1",
      "Name": "united states"
    },
    {
      "Capital": "Beijing",
      "Largest city": "Shanghai",
      "Official languages": "Standard Chinese",
      "Official script": "Simplified Chinese",
      "Ethnic groups": "91.1% Han Chinese",
      "Religion": "74.5% no religion / folk",
      "Government": "Unitary Marxist–Leninist one-party socialist republic",
      "Legislature": "National People's Congress",
      "Gini": "37.1",
      "HDI": "0.768",
      "Currency": "Renminbi",
      "Time zone": "UTC+8",
      "Date format": "yyyy-mm-dd",
      "Driving side": "right",
      "Calling code": "+86",
      "Name": "china"
    },
    {
      "Capital": "Islamabad",
      "Largest city": "Karachi",
      "Official languages": "Urdu English",
      "Native languages": "Over 77 languages",
      "Religion": "96.5% Islam",
      "Government": "Federal Islamic parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "31.6",
      "HDI": "0.544",
      "Currency": "Rupee",
      "Time zone": "UTC+05:00",
      "Date format": "dd-mm-yyyy",
      "Driving side": "left",
      "Calling code": "+92",
      "Name": "pakistan"
    },
    {
      "Capital": "Jakarta",
      "Official language": "Indonesian",
      "Regional languages": "Over 700 languages",
      "Ethnic groups": "Over 1,300 ethnic groups",
      "Religion": "87% Islam",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "People's Consultative Assembly",
      "Gini": "37.9",
      "HDI": "0.705",
      "Currency": "Rupiah",
      "Time zone": "UTC+7 to +9",
      "Date format": "DD/MM/YYYY",
      "Driving side": "left",
      "Calling code": "+62",
      "Name": "indonesia"
    },
    {
      "Capital": "New Delhi",
      "Largest city": "Mumbai",
      "Official languages": "HindiEnglish",
      "Native languages": "447 languages",
      "Religion": "79.8% Hinduism",
      "Government": "Federal parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "35.7",
      "HDI": "0.633",
      "Currency": "₹",
      "Time zone": "UTC+05:30",
      "Date format": "dd-mm-yyyy",
      "Driving side": "left",
      "Calling code": "+91",
      "Emblem": "Sarnath Lion Capital",
      "Anthem": "Jana Gana Mana",
      "Song": "\"Vande Mataram\"",
      "Language": "None",
      "Calendar": "Shaka",
      "Bird": "Indian peafowl",
      "Flower": "Lotus",
      "Fruit": "Mango",
      "Mammal": "Bengal tiger",
      "Tree": "Banyan",
      "River": "Ganges",
      "Name": "india"
    },
    {
      "Capital": "Mexico City",
      "Official languages": "Spanish",
      "Co-official languages": "68 Indigenous languages",
      "Religion": "71% Christianity",
      "Government": "Federal presidential republic",
      "Legislature": "Congress",
      "Gini": "41.8",
      "HDI": "0.758",
      "Currency": "Peso",
      "Time zone": "UTC−8 to −5",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+52",
      "Name": "mexico"
    },
    {
      "Capital": "Moscow",
      "Official and national language": "Russian",
      "Ethnic groups": "71.7% Russian",
      "Religion": "61% Christianity",
      "Government": "Federal semi-presidential republic under an authoritarian dictatorship",
      "Legislature": "Federal Assembly",
      "Gini": "36.0",
      "HDI": "0.822",
      "Currency": "Ruble",
      "Time zone": "UTC+2 to +12",
      "Driving side": "right",
      "Calling code": "+7",
      "Name": "russia"
    },
    {
      "Capital": "Dhaka",
      "Official language": "Bengali",
      "Ethnic groups": "98.2–99% Bengalis",
      "Religion": "91.04% Islam",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Jatiya Sangsad",
      "Gini": "49.9",
      "HDI": "0.661",
      "Currency": "Taka",
      "Time zone": "UTC+6",
      "Driving side": "left",
      "Calling code": "+880",
      "Name": "bangladesh"
    },
    {
      "Capital": "Brasília",
      "Largest city": "São Paulo",
      "Official language": "Portuguese",
      "Recognized regional languages": "21 languages",
      "Ethnic groups": "45.3% Mixed",
      "Religion": "79.1% Christianity",
      "Government": "Federal presidential republic",
      "Legislature": "National Congress",
      "Gini": "48.9",
      "HDI": "0.754",
      "Currency": "Real",
      "Time zone": "UTC−2 to −5",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+55",
      "Name": "brazil"
    },
    {
      "Capital": "Tokyo",
      "Official languages": "Japanese",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "National Diet",
      "Gini": "33.4",
      "HDI": "0.925",
      "Currency": "Yen",
      "Time zone": "UTC+09:00",
      "Driving side": "left",
      "Calling code": "+81",
      "Name": "japan"
    },
    {
      "Capital": "Manila",
      "Largest city": "Quezon City",
      "Official languages": "FilipinoEnglish",
      "Recognized regional languages": "19 languages",
      "National sign language": "Filipino Sign Language",
      "Other recognized languages[b]": "Spanish and Arabic",
      "Ethnic groups": "33.7% Visayan",
      "Religion": "90.1% Christianity",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "Congress",
      "Gini": "41.2",
      "HDI": "0.699",
      "Currency": "Peso",
      "Time zone": "UTC+08:00",
      "Driving side": "right",
      "Calling code": "+63",
      "Name": "philippines"
    },
    {
      "Capital": "Addis Ababa",
      "Official languages": "Afar",
      "Regional languages[4]": "Harari Sidama",
      "Ethnic groups": "34.5% Oromo",
      "Religion": "67.3% Christianity",
      "Government": "Federal parliamentary republic",
      "Legislature": "Federal Parliamentary Assembly",
      "Gini": "35.0",
      "HDI": "0.498",
      "Currency": "Birr",
      "Time zone": "UTC+3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+251",
      "Name": "ethiopia"
    },
    {
      "Capital": "Hanoi",
      "Largest city": "Ho Chi Minh City",
      "Official language": "Vietnamese",
      "Ethnic groups": "85.32% Kinh Vietnamese",
      "Religion": "73.7% no religion / folk",
      "Government": "Socialist republic",
      "Legislature": "National Assembly",
      "Gini": "35.7",
      "HDI": "0.703",
      "Currency": "Dồng",
      "Time zone": "UTC+07:00",
      "Driving side": "right",
      "Calling code": "+84",
      "Name": "vietnam"
    },
    {
      "Capital": "Cairo",
      "Official languages": "Arabic",
      "National language": "Egyptian Arabic",
      "Government": "Unitary semi-presidential republic under an authoritarian regime",
      "Legislature": "Parliament",
      "Gini": "31.5",
      "HDI": "0.731",
      "Currency": "Pound",
      "Time zone": "UTC+2",
      "Driving side": "right",
      "Calling code": "+20",
      "Name": "egypt"
    },
    {
      "Capital": "Ankara",
      "Largest city": "Istanbul",
      "Official languages": "Turkish",
      "Spoken languages": "Predominantly Turkish",
      "Ethnic groups": "70–75% Turks",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "Grand National Assembly",
      "Gini": "41.9",
      "HDI": "0.838",
      "Currency": "Lira",
      "Time zone": "UTC+3",
      "Calling code": "+90",
      "Name": "turkey"
    },
    {
      "Capital": "Kinshasa",
      "Official languages": "French",
      "Recognised national languages": "Kituba",
      "Religion": "95.4% Christianity",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "42.1",
      "HDI": "0.479",
      "Currency": "Franc",
      "Time zone": "UTC+1 to +2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Name": "democratic republic of the congo"
    },
    {
      "Capital": "Tehran",
      "Official languages": "Persian",
      "Religion": "99% Islam",
      "Government": "Unitary presidential theocratic Islamic republic",
      "Legislature": "Islamic Consultative Assembly",
      "Gini": "40.9",
      "HDI": "0.774",
      "Currency": "Rial",
      "Time zone": "UTC+3:30",
      "Date format": "yyyy/mm/dd",
      "Driving side": "right",
      "Calling code": "+98",
      "Name": "iran"
    },
    {
      "Capital": "Berlin",
      "Official languages": "German",
      "Government": "Federal parliamentary republic",
      "Legislature": "Bundestag, Bundesrat",
      "Gini": "28.8",
      "HDI": "0.942",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "Day, month, yearYear, month, day",
      "Driving side": "right",
      "Calling code": "+49",
      "Name": "germany"
    },
    {
      "Capital": "Paris",
      "Official language": "French",
      "Nationality": "92.2% French",
      "Religion": "53% no religion",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "29.8",
      "HDI": "0.903",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+33",
      "Name": "france"
    },
    {
      "Capital": "Bangkok",
      "Official language": "Thai",
      "Spoken languages": "Thai, Isan, Lanna, Dambro, Karen, Pattani",
      "Ethnic groups": "80% Thai",
      "Religion": "90% Buddhism",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "National Assembly",
      "Gini": "35.1",
      "HDI": "0.800",
      "Currency": "Baht",
      "Time zone": "UTC+7",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+66",
      "Name": "thailand"
    },
    {
      "Capital": "London",
      "Official language": "English",
      "Regional and minority languages": "Scots Ulster Scots Welsh Cornish Scottish",
      "Ethnic groups": "87.1% White",
      "Constituent countries": "England",
      "Government": "Unitary",
      "Legislature": "Parliament",
      "Gini": "35.5",
      "HDI": "0.929",
      "Currency": "Pound",
      "Time zone": "UTC+0",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+44",
      "Name": "united kingdom"
    },
    {
      "Capital": "Rome",
      "Official languages": "Italiana",
      "Nationality": "91.3% Italian",
      "Religion": "84.4% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "32.5",
      "HDI": "0.895",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+39c",
      "Name": "italy"
    },
    {
      "Capital": "Dodoma",
      "Largest city": "Dar es Salaam",
      "Official languages": "SwahiliEnglish",
      "National language": "Swahili",
      "Other languages": "Over 100 languages, including",
      "Ethnic groups": "Over 100 ethnic groups",
      "Religion": "63.1% Christianity",
      "Government": "Unitary socialist",
      "Legislature": "National Assembly",
      "Gini": "40.5",
      "HDI": "0.550",
      "Currency": "Shilling",
      "Time zone": "UTC+3",
      "Driving side": "left",
      "Calling code": "+255",
      "Name": "tanzania"
    },
    {
      "Zulu:": "iRiphabhuliki yaseNingizimu Afrika",
      "Xhosa:": "iRiphabhlikhi yoMzantsi Afrika",
      "Afrikaans:": "Republiek van Suid-Afrika",
      "Pedi:": "Repabliki ya Afrika-Borwa",
      "Southern Sotho:": "Rephaboliki ya Afrika Borwa",
      "Tswana:": "Rephaboliki ya Aforika Borwa",
      "Tsonga:": "Riphabliki ya Afrika Dzonga",
      "Swati:": "iRiphabhulikhi yaseNingizimu-Afrika",
      "Venda:": "Riphabuḽiki ya Afurika Tshipembe",
      "Southern Ndebele:": "iRiphabliki yeSewula Afrika",
      "Capital": "Pretoria",
      "Largest city": "Johannesburg",
      "Official languages": "12 languages",
      "Ethnic groups": "81.4% Black",
      "Religion": "78.0% Christianity",
      "Government": "Unitary parliamentary republic with an executive presidency",
      "Legislature": "Parliament",
      "Gini": "63.0",
      "HDI": "0.713",
      "Currency": "Rand",
      "Time zone": "UTC+2",
      "Date format": "Short formats:",
      "Driving side": "left",
      "Calling code": "+27",
      "Name": "south africa"
    },
    {
      "Capital": "Naypyidaw",
      "Largest city": "Yangon",
      "Official language": "Burmese",
      "Recognised regional languages[1]": "Chin Kachin Karen Kayah",
      "Ethnic groups": "68% Bamar",
      "Religion": "87.9% Buddhism",
      "Government": "Unitary assembly-independent republic under a military junta",
      "Legislature": "State Administration Council",
      "Gini": "30.7",
      "HDI": "0.585",
      "Currency": "Kyat",
      "Time zone": "UTC+06:30",
      "Driving side": "right",
      "Calling code": "+95",
      "Name": "myanmar"
    },
    {
      "Capital": "Bogotá",
      "Official languages": "Spanish",
      "Recognized regional languages": "Creole English",
      "Ethnic groups": "87.58% Mestizo-White",
      "Religion": "87.0% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Congress",
      "Gini": "54.2",
      "HDI": "0.752",
      "Currency": "Peso",
      "Time zone": "UTC−5",
      "Date format": "dd-mm-yyyy",
      "Driving side": "right",
      "Calling code": "+57",
      "Name": "colombia"
    },
    {
      "Catalan:": "Regne d'Espanya",
      "Basque:": "Espainiako Erresuma",
      "Galician:": "Reino de España",
      "Occitan:": "Reiaume d'Espanha",
      "Capital": "Madrid",
      "Official language": "Spanish",
      "Nationality": "87.1% Spanish",
      "Religion": "56.0% Roman Catholicism",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Cortes Generales",
      "Gini": "32.0",
      "HDI": "0.905",
      "Currency": "Euro",
      "Time zone": "UTC⁠±0 to +1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+34",
      "Name": "spain"
    },
    {
      "Capital": "Seoul",
      "Official languages": "Korean",
      "Official script": "Hangul",
      "Ethnic groups": "95.1% Korean",
      "Religion": "56.1% no religion",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "National Assembly",
      "Gini": "33.3",
      "HDI": "0.925",
      "Currency": "Won",
      "Time zone": "UTC+9",
      "Date format": "yyyy년 m월 d일",
      "Driving side": "right",
      "Calling code": "+82",
      "Name": "south korea"
    },
    {
      "Capital": "Nairobi",
      "Official languages": "Swahili English",
      "National language": "Swahili",
      "Ethnic groups": "17.13% Kikuyu",
      "Religion": "85.5% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Parliament",
      "Gini": "38.7",
      "HDI": "0.575",
      "Currency": "Shilling",
      "Time zone": "UTC+3",
      "Date format": "dd/mm/yy",
      "Driving side": "left",
      "Calling code": "+254",
      "Name": "kenya"
    },
    {
      "Capital": "Buenos Aires",
      "Official languages": "Spanish",
      "Co-official languages": "Guaraní in Corrientes",
      "Religion": "58.9% Christianity",
      "Government": "Federal presidential constitutional republic",
      "Legislature": "National Congress",
      "Gini": "42.3",
      "HDI": "0.842",
      "Currency": "Peso",
      "Time zone": "UTC−3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+54",
      "Name": "argentina"
    },
    {
      "Luganda:": "Lipabuliika ya Uganda",
      "Lusoga:": "Uganda Eryetwala",
      "Lumasaba:": "Linambo lya Uganda",
      "Capital": "Kampala",
      "Official languages": "English Swahili",
      "Religion": "82% Christianity",
      "Government": "Unitary dominant-party presidential republic",
      "Legislature": "Parliament",
      "Gini": "42.0",
      "HDI": "0.525",
      "Currency": "Shilling",
      "Time zone": "UTC+3",
      "Driving side": "left",
      "Calling code": "+256a",
      "Name": "uganda"
    },
    {
      "Capital": "Algiers",
      "Official languages": "Arabic",
      "Other languages": "Algerian Arabic",
      "Ethnic groups": "75%–85% Arabs",
      "Religion": "99% Sunni Islam",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "27.6",
      "HDI": "0.745",
      "Currency": "Dinar",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+213",
      "Name": "algeria"
    },
    {
      "Capital": "Kyiv",
      "Official language": "Ukrainian",
      "Ethnic groups": "78% Ukrainians",
      "Religion": "87.3% Christianity",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Verkhovna Rada",
      "Gini": "25.6",
      "HDI": "0.773",
      "Currency": "Hryvnia",
      "Time zone": "UTC+2",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+380",
      "Name": "ukraine"
    },
    {
      "Capital": "Baghdad",
      "Official languages": "ArabicKurdish",
      "Recognised regional languages": "Suret",
      "Ethnic groups": "75–80% Arabs",
      "Government": "Federal parliamentary republic",
      "Legislature": "Council of Representatives",
      "Gini": "29.5",
      "HDI": "0.686",
      "Currency": "Dinar",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+964",
      "Name": "iraq"
    },
    {
      "Capital": "Khartoum",
      "Capital-in-exile": "Port Sudan",
      "Official languages": "Arabic, English",
      "Recognised national languages": "Sudanese Arabic",
      "Ethnic groups": "70% Sudanese Arab",
      "Religion": "97% Sunni Islam",
      "Government": "Federal republic under a military junta",
      "Legislature": "Vacant",
      "Gini": "34.2",
      "HDI": "0.508",
      "Currency": "Pound",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+249",
      "Name": "sudan"
    },
    {
      "Capital": "Ottawa",
      "Largest city": "Toronto",
      "Official languages": "English French",
      "Government": "Federal parliamentary constitutional monarchy",
      "Legislature": "Parliament",
      "Gini": "30.3",
      "HDI": "0.936",
      "Currency": "Dollar",
      "Time zone": "UTC−3.5 to −8",
      "Date format": "yyyy-mm-dd",
      "Calling code": "+1",
      "Name": "canada"
    },
    {
      "Capital": "Warsaw",
      "Official language": "Polish",
      "Ethnic groups": "98% Poles",
      "Religion": "72.2% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "27.2",
      "HDI": "0.876",
      "Currency": "Złoty",
      "Time zone": "UTC+1",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+48",
      "Name": "poland"
    },
    {
      "Status": "UN member state under an unrecognized government",
      "Capital": "Kabul",
      "Official languages": "PashtoDari",
      "Ethnic groups": "42% Pashtun",
      "Religion": "99.7% Islam",
      "Government": "Unitary totalitarian",
      "Legislature": "None",
      "HDI": "0.478",
      "Currency": "Afghani",
      "Time zone": "UTC+4:30",
      "Name": "afghanistan"
    },
    {
      "Capital": "Tashkent",
      "Official languages": "Uzbek",
      "Recognised regional languages": "Karakalpak",
      "Spoken languages": "Uzbek • Tajik • Kazakh• Karakalpak",
      "Ethnic groups": "84.5% Uzbeks",
      "Religion": "96.1% Islam",
      "Government": "Unitary presidential republic",
      "Legislature": "Oliy Majlis",
      "Gini": "36.7",
      "HDI": "0.727",
      "Currency": "Sum",
      "Time zone": "UTC+5",
      "Date format": "dd/mm yyyyc",
      "Driving side": "right",
      "Calling code": "+998",
      "Name": "uzbekistan"
    },
    {
      "Capital": "Rabat",
      "Largest city": "Casablanca",
      "Official languages": "ArabicTamazight",
      "Spoken languages": "Moroccan Arabic",
      "Foreign languages": "EnglishSpanish",
      "Ethnic groups": "67% Arabs",
      "Religion [1][5]": "99.6% Islam",
      "Government": "Unitary parliamentary semi-constitutional monarchy",
      "Legislature": "Parliament",
      "Gini": "40.3",
      "HDI": "0.683",
      "Currency": "Dirham",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+212",
      "Name": "morocco"
    },
    {
      "Quechua:": "Piruw Ripuwlika",
      "Aymara:": "Piruwxa Ripuwlika",
      "Capital": "Lima",
      "Official languages": "Spanish",
      "Co-official languages": "Quechua",
      "Ethnic groups": "60.2% Mestizo",
      "Religion": "94.5% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Congress of the Republic",
      "Gini": "41.5",
      "HDI": "0.762",
      "Currency": "Sol",
      "Time zone": "UTC−5",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+51",
      "Name": "peru"
    },
    {
      "Capital": "Kuala Lumpur",
      "Administrative center": "Putrajaya",
      "Official languages": "Malay",
      "Recognised language": "English",
      "Ethnic groups": "69.7% Bumiputera",
      "Religion": "63.5% Sunni Islam",
      "Government": "Federal parliamentary constitutional elective monarchy",
      "Legislature": "Parliament",
      "Gini": "41.2",
      "HDI": "0.803",
      "Currency": "Ringgit",
      "Time zone": "UTC+8",
      "Date format": "dd-mm-yyyy",
      "Driving side": "left",
      "Calling code": "+60",
      "Name": "malaysia"
    },
    {
      "Capital": "Maputo",
      "Official languages": "Portuguese",
      "Recognised regional languages": "Makhuwa, Sena, Tsonga, Lomwe, Changana",
      "Ethnic groups": "99% Black African",
      "Religion": "55.8% Christianity",
      "Government": "Unitary dominant-party semi-presidential republic under an authoritarian government",
      "Legislature": "Assembly of the Republic",
      "Gini": "54.0",
      "HDI": "0.446",
      "Currency": "Metical",
      "Time zone": "UTC+2",
      "Calling code": "+258",
      "Name": "mozambique"
    },
    {
      "Capital": "Luanda",
      "Official language": "Portuguese",
      "National languages": "Kimbundu",
      "Ethnic groups": "37% Ovimbundu",
      "Religion": "92.9% Christianity",
      "Government": "Unitary dominant-party parliamentary republic with an executive presidency under an authoritarian government",
      "Legislature": "National Assembly",
      "Gini": "51.3",
      "HDI": "0.588",
      "Currency": "Kwanza",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+244",
      "Name": "angola"
    },
    {
      "Capital": "Riyadh",
      "Official languages": "Arabic",
      "Ethnic groups": "90% Arab",
      "Religion": "93.0% Islam",
      "Government": "Unitary Islamic absolute monarchy",
      "Legislature": "none",
      "Gini": "45.9",
      "HDI": "0.875",
      "Currency": "Riyal",
      "Time zone": "UTC+3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+966",
      "Name": "saudi arabia"
    },
    {
      "Status": "Yemeni Civil War",
      "Capital": "Sanaa",
      "Capital-in-exile": "Aden",
      "Official language": "Arabic",
      "Ethnic groups": "92.8% Yemenis",
      "Religion": "~99.1% Islam",
      "Government": "Unitary provisional republic",
      "Legislature": "Parliament",
      "Gini": "36.7",
      "HDI": "0.455",
      "Currency": "Rial",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+967",
      "Name": "yemen"
    },
    {
      "Capital": "Accra",
      "Official languages": "English",
      "Ethnic groups": "45.7% Akans",
      "Religion": "71.3% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Parliament",
      "Gini": "43.5",
      "HDI": "0.632",
      "Currency": "Cedi",
      "Time zone": "UTC",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+233",
      "Name": "ghana"
    },
    {
      "Capital": "Yamoussoukro",
      "Largest city": "Abidjan",
      "Official languages": "French",
      "Vernacular": "BétéJulaBauleAbronAnyinCebaara Senufoothers",
      "Ethnic groups": "78.0% Ivorian",
      "Government": "Unitary presidential republic",
      "Legislature": "Parliament of Ivory Coast",
      "Gini": "41.5",
      "HDI": "0.550",
      "Currency": "West African CFA franc",
      "Time zone": "UTC±00:00",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+225",
      "Name": "ivory coast"
    },
    {
      "Capital": "Kathmandu",
      "Official languages": "Nepali",
      "Recognised national languages": "All mother-tongues",
      "Ethnic groups": "31.25% Khas Arya",
      "Religion": "81.19% Hinduism",
      "Government": "Federal parliamentary republic",
      "Legislature": "Federal Parliament",
      "Gini": "32.8",
      "HDI": "0.602",
      "Currency": "Rupee",
      "Time zone": "UTC+05:45",
      "Date format": "YYYY/MM/DD",
      "Driving side": "left",
      "Calling code": "+977",
      "Emblem": "Emblem of Nepal",
      "Anthem": "Sayaun Thunga Phulka",
      "Language": "All mother-tongues of Nepal",
      "Bird": "Himalayan monal",
      "Flower": "Rhododendron arboreum",
      "Mammal": "Cow",
      "Colour": "Crimson",
      "Sport": "Volleyball",
      "Name": "nepal"
    },
    {
      "Capital": "Yaoundé",
      "Largest city": "Douala",
      "Official languages": "French • English",
      "Ethnic groups": "24.3% Bamileke-Bamum",
      "Religion": "59.7% Christianity",
      "Government": "Unitary dominant-party presidential republic",
      "Legislature": "Parliament",
      "Gini": "46.6",
      "HDI": "0.594",
      "Currency": "Central African CFA franc",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+237",
      "Name": "cameroon"
    },
    {
      "Capital": "Caracas",
      "Official languages": "Spanish",
      "Ethnic groups": "51.6% Multiracial",
      "Religion": "92.6% Christianity",
      "Government": "Federal presidential republic under a centralized authoritarian state",
      "Legislature": "National Assembly",
      "Gini": "44.8",
      "HDI": "0.691",
      "Currency": "Bolívar",
      "Time zone": "UTC−4",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+58",
      "Name": "venezuela"
    },
    {
      "Capital": "Antananarivo",
      "Official languages": "Malagasy • French",
      "Ethnic groups": "26% Merina",
      "Religion": "84.7% Christianity",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "42.6",
      "HDI": "0.501",
      "Currency": "Ariary",
      "Time zone": "UTC+3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+261",
      "Name": "madagascar"
    },
    {
      "Capital": "Canberra",
      "Largest city": "Sydney",
      "Official languages": "None at the federal level",
      "National language": "English",
      "Religion": "43.9% Christianity",
      "Government": "Federal parliamentary constitutional monarchy",
      "Legislature": "Parliament",
      "Gini": "32.5",
      "HDI": "0.951",
      "Currency": "Dollar",
      "Time zone": "UTC+8; +9.5; +10",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+61",
      "Name": "australia"
    },
    {
      "Capital": "Pyongyang",
      "Official languages": "Korean",
      "Official script": "Chosŏn'gŭl",
      "Religion": "73% no religion",
      "Government": "Unitary one-party socialist republic under a totalitarian hereditary dictatorship",
      "Legislature": "Supreme People's Assembly",
      "Currency": "Won",
      "Time zone": "UTC+9",
      "Date format": "yy, yyyy년 mm월 dd일",
      "Driving side": "right",
      "Calling code": "+850",
      "Name": "north korea"
    },
    {
      "Capital": "Niamey",
      "Official languages": "French",
      "National languages[1]": "Arabic Buduma",
      "Ethnic groups": "53.1% Hausa",
      "Religion": "99.3% Islam",
      "Government": "Unitary republic under a military junta",
      "Legislature": "National Council for the Safeguard of the Homeland",
      "Gini": "34.0",
      "HDI": "0.400",
      "Currency": "West African CFA franc",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+227",
      "Name": "niger"
    },
    {
      "Capital": "Taipei",
      "Largest city": "New Taipei City",
      "Official languages": "Standard Chinese",
      "Official script": "Traditional Chinese",
      "National languages[e]": "Mandarin",
      "Ethnic groups": "95–97% Han Taiwanese",
      "Religion": "35.1% Buddhism",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Legislative Yuan",
      "Gini": "34.1",
      "HDI": "0.926",
      "Currency": "Dollar",
      "Time zone": "UTC+8",
      "Name": "taiwan"
    },
    {
      "Capital": "Damascus",
      "Official languages": "Arabic",
      "Ethnic groups": "74–75% Arabs",
      "Religion": "77% Islam",
      "Government": "Unitary presidential republic",
      "Legislature": "People's Assembly",
      "Gini": "55.8",
      "HDI": "0.577",
      "Currency": "Pound",
      "Time zone": "UTC+3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+963",
      "Name": "syria"
    },
    {
      "Bambara:": "Mali ka Fasojamana",
      "Fula:": "Republik bu Maali",
      "Hassaniyya:": "جُمْهُورِيَّةْ مَالِي",
      "Soninke:": "Mali Tɔgɔbadugu",
      "Tamasheq:": "ⵜⴰⴳⴷⵓⴷⴰ ⵏ ⵎⴰⵍⵉ",
      "Capital": "Bamako",
      "Official languages": "13 national languages",
      "Working language": "French",
      "Spoken languages": "BambaraBoboBozoDogonFrenchFulaHassaniya ArabicKassonkeManinkeMinyankaSenufoSonghaySoninkeTamasheqMandinkaMaureDafingSamogoHausa",
      "Ethnic groups": "33.3% Bambara",
      "Religion": "95% Islam",
      "Government": "Unitary presidential republic under a military junta",
      "Legislature": "National Assembly",
      "Gini": "33.0",
      "HDI": "0.428",
      "Currency": "West African CFA franc",
      "Time zone": "UTC",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+223",
      "Name": "mali"
    },
    {
      "Capital": "Ouagadougou",
      "Recognised national languages": "Mooré",
      "Ethnic groups": "52% Mossi",
      "Government": "Unitary republic under a military junta",
      "Legislature": "Transitional Legislative Assembly",
      "Gini": "38.9",
      "HDI": "0.449",
      "Currency": "West African CFA franc",
      "Time zone": "UTC+00:00",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+226",
      "Name": "burkina faso"
    },
    {
      "Sinhala:": "Śrī Laṅkā Prajātāntrika Samājavādī Janarajaya",
      "Tamil:": "Ilaṅkai Jaṉanāyaka Sōsalisak Kuṭiyarasu",
      "Capital": "Sri Jayawardenepura Kotte",
      "Largest city": "Colombo",
      "Official languages": "Sinhala",
      "Recognised languages": "English",
      "Ethnic groups": "74.9% Sinhalese",
      "Religion": "70.2% Buddhism",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "39.8",
      "HDI": "0.782",
      "Currency": "Rupee",
      "Time zone": "UTC+5:30",
      "Driving side": "left",
      "Calling code": "+94",
      "Flag": "Lion Flag",
      "Emblem": "Gold Lion Passant",
      "Anthem": "\"Sri Lanka Matha\"",
      "Butterfly": "Sri Lankan birdwing",
      "Animal": "Grizzled giant squirrel",
      "Bird": "Sri Lanka junglefowl",
      "Flower": "Blue water lily",
      "Tree": "Ceylon ironwood",
      "Sport": "Volleyball",
      "Name": "sri lanka"
    },
    {
      "Capital": "Lilongwe",
      "Official languages": "English",
      "Recognised regional languages": "Chewa",
      "Ethnic groups": "25.2% Chewa",
      "Religion": "82.3% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "44.7",
      "HDI": "0.512",
      "Currency": "Kwacha",
      "Time zone": "UTC+2",
      "Calling code": "+265",
      "Name": "malawi"
    },
    {
      "Capital": "Santiagoa",
      "National language": "Spanish",
      "Religion": "62.1% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Congress",
      "Gini": "46",
      "HDI": "0.855",
      "Currency": "Peso",
      "Time zone": "UTC−4 and −6",
      "Driving side": "right",
      "Calling code": "+56",
      "Name": "chile"
    },
    {
      "Capital": "Lusaka",
      "Official languages": "English",
      "Religion": "Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "57.1",
      "HDI": "0.584",
      "Currency": "Kwacha",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+260",
      "Name": "zambia"
    },
    {
      "Capital": "Bucharest",
      "Official languages": "Romanian",
      "Ethnic groups": "89.3% Romanians",
      "Religion": "84.8% Christianity",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "34.3",
      "HDI": "0.821",
      "Currency": "Leu",
      "Time zone": "UTC+2",
      "Name": "romania"
    },
    {
      "Capital": "Mogadishu",
      "Official languages": "Somali, Arabic",
      "Ethnic groups": "Somali 85%",
      "Religion": "Sunni Islam",
      "Government": "Federal parliamentary constitutional republic",
      "Legislature": "Federal Parliament",
      "HDI": "0.361",
      "Currency": "Shilling",
      "Time zone": "UTC+3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+252",
      "Name": "somalia"
    },
    {
      "Capital": "Dakar",
      "Official languages": "French",
      "National languages": "Wolof Serer Diola Hassaniya",
      "Lingua franca": "Wolof",
      "Ethnic groups": "39.7% Wolof",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "40.3",
      "HDI": "0.511",
      "Currency": "West African CFA franc",
      "Time zone": "UTC",
      "Date format": "mm/dd/yyyy",
      "Driving side": "right",
      "Calling code": "+221",
      "Name": "senegal"
    },
    {
      "Capital": "Guatemala City",
      "Official languages": "Spanish",
      "Ethnic groups": "56.01% Ladino / Mestizo",
      "Religion": "88% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Congress of the Republic",
      "Gini": "48.3",
      "HDI": "0.627",
      "Currency": "Quetzal",
      "Time zone": "UTC−6",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+502",
      "Name": "guatemala"
    },
    {
      "Sovereign state": "Kingdom of the Netherlands",
      "Before independence": "Spanish Netherlands",
      "Act of Abjuration": "26 July 1581",
      "Peace of Münster": "30 January 1648",
      "Kingdom established": "16 March 1815",
      "Liberation Day": "5 May 1945",
      "Kingdom Charter": "15 December 1954",
      "Caribbean reorganisation": "10 October 2010",
      "Capital": "Amsterdam",
      "Government seat": "The Hague",
      "Official languages": "Dutch",
      "Regional languages": "West Frisian Papiamento English",
      "Recognised languages": "Dutch Low SaxonDutch Sign LanguageLimburgishSinte RomaniYiddish",
      "Ethnic groups": "74.0% Dutch",
      "Religion": "55.4% no religion",
      "Government": "Parliamentary constitutional monarchy",
      "Legislature": "States General",
      "Highest elevation": "322.4 m",
      "Gini": "26.4",
      "HDI": "0.941",
      "Currency": "Euro",
      "Time zone": "UTC+01:00",
      "Driving side": "right",
      "Calling code": "+31, +599",
      "Name": "netherlands"
    },
    {
      "Capital": "Phnom Penh",
      "Official language": "Khmer",
      "Official script": "Khmer",
      "Ethnic groups": "95.6% Khmer",
      "Religion": "97.1% Buddhism",
      "Government": "Unitary parliamentary constitutional monarchy under a hereditary dictatorship",
      "Legislature": "Parliament",
      "Gini": "36.0",
      "HDI": "0.593",
      "Currency": "Riel",
      "Time zone": "UTC+07:00",
      "Driving side": "right",
      "Calling code": "+855",
      "Name": "cambodia"
    },
    {
      "Capital": "N'Djamena",
      "Official languages": "ArabicFrench",
      "Ethnic groups": "26.6% Sara",
      "Religion": "55.1% Islam",
      "Government": "Unitary republic under a military junta",
      "Legislature": "National Transitional Council",
      "Gini": "37.5",
      "HDI": "0.394",
      "Currency": "Central African CFA franc",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+235",
      "Name": "chad"
    },
    {
      "Capital": "Quito",
      "Largest city": "Guayaquil",
      "Official languages": "Spanish",
      "Recognized regional languages": "Kichwa",
      "Ethnic groups": "77.5% Mestizo",
      "Religion": "86.7% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "45.5",
      "HDI": "0.740",
      "Currency": "Dollar",
      "Time zone": "UTC−5 / −6",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+593",
      "Name": "ecuador"
    },
    {
      "Capital": "Harare",
      "Official languages": "16 languages:",
      "Ethnic groups": "99.38% African",
      "Religion": "84.1% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Parliament",
      "Gini": "50.3",
      "HDI": "0.593",
      "Currency": "Dollar",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+263",
      "Name": "zimbabwe"
    },
    {
      "Capital": "Conakry",
      "Official languages": "French",
      "Ethnic groups": "33.4% Fula",
      "Government": "Unitary presidential republic under a military junta",
      "Legislature": "National Council of the Transition",
      "Gini": "33.7",
      "HDI": "0.465",
      "Currency": "Franc",
      "Time zone": "UTC",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+224",
      "Name": "guinea"
    },
    {
      "Capital": "Kigali",
      "Official languages": "Kinyarwanda",
      "Ethnic groups": "99% Banyarwanda",
      "Religion": "93.8% Christianity",
      "Government": "Unitary presidential republic under an authoritarian dictatorship",
      "Legislature": "Parliament",
      "Gini": "43.7",
      "HDI": "0.534",
      "Currency": "Franc",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+250",
      "Name": "rwanda"
    },
    {
      "Capital": "Juba",
      "Official languages": "English",
      "Recognised national languages": "Dinka Nuer Bari MurleLuo",
      "Spoken languages[7]": "DinkaBariJuba Arabic",
      "Religion": "60.5% Christianity",
      "Government": "Federal transitional presidential republic",
      "Legislature": "Transitional National Legislature",
      "Gini": "44.1",
      "HDI": "0.379",
      "Currency": "Pound",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+211",
      "Name": "south sudan"
    },
    {
      "Capital": "Gitega",
      "Largest city": "Bujumbura",
      "Official languages": "Kirundi",
      "Ethnic groups": "99% Barundi",
      "Religion": "93.4% Christianity",
      "Government": "Unitary dominant-party presidential republic under an authoritarian state",
      "Legislature": "Parliament",
      "Gini": "39.2",
      "HDI": "0.426",
      "Currency": "Franc",
      "Time zone": "UTC+2",
      "Driving side": "right",
      "Name": "burundi"
    },
    {
      "Capital": "Porto-Novo",
      "Largest city": "Cotonou",
      "Official languages": "French",
      "Ethnic groups": "38.4% Fon",
      "Religion": "52.2% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "47.8",
      "HDI": "0.525",
      "Currency": "West African CFA franc",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+229",
      "Name": "benin"
    },
    {
      "Capital": "Sucre",
      "Administrative center": "La Paz",
      "Largest city": "Santa Cruz de la Sierra",
      "Official languages": "Spanish",
      "Ethnic groups": "68% Mestizo",
      "Religion": "89.3% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Plurinational Legislative Assembly",
      "Gini": "41.6",
      "HDI": "0.692",
      "Currency": "Boliviano",
      "Time zone": "UTC−4",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+591",
      "Name": "bolivia"
    },
    {
      "Capital": "Tunis",
      "Official languages": "Arabic",
      "Local vernacular": "Tunisian Arabic",
      "Foreign languages": "French",
      "Ethnic groups": "98% Arabs",
      "Religion": "99% Sunni Islam",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Assembly of the Representatives of the People",
      "Gini": "35.8",
      "HDI": "0.731",
      "Currency": "Dinar",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+216",
      "Name": "tunisia"
    },
    {
      "Capital": "Brussels",
      "Official languages": "Dutch",
      "Ethnic groups": "66.6% Belgians",
      "Religion": "63.7% Christianity",
      "Government": "Federal parliamentary constitutional monarchy",
      "Legislature": "Federal Parliament",
      "Gini": "24.9",
      "HDI": "0.937",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+32",
      "Name": "belgium"
    },
    {
      "Capital": "Port Moresby",
      "Official languages[3][4]": "EnglishHiri MotuPNG Sign LanguageTok Pisin",
      "Indigenous languages": "851 languages",
      "Ethnic groups": "Papuan",
      "Religion": "95.5% Christianity",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "National Parliament",
      "Gini": "41.9",
      "HDI": "0.558",
      "Currency": "Kina",
      "Time zone": "UTC+10, +11",
      "Driving side": "left",
      "Calling code": "+675",
      "Name": "papua new guinea"
    },
    {
      "Capital": "Port-au-Prince",
      "Official languages": "French",
      "Ethnic groups": "95% Black",
      "Religion": "87.0% Christianity",
      "Government": "Unitary semi-presidential republic under an interim government",
      "Legislature": "National Assembly",
      "Gini": "41.1",
      "HDI": "0.535",
      "Currency": "Gourde",
      "Time zone": "UTC−5",
      "Driving side": "right",
      "Calling code": "+509",
      "Name": "haiti"
    },
    {
      "Capital": "Amman",
      "Official languages": "Arabic",
      "Ethnic groups": "95% Arab",
      "Religion": "95% Sunni Islam",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Parliament",
      "Gini": "35.4",
      "HDI": "0.720",
      "Currency": "Dinar",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+962",
      "Name": "jordan"
    },
    {
      "Capital": "Havana",
      "Official languages": "Spanish",
      "Other spoken languages": "Haitian Creole",
      "Ethnic groups": "64.1% White",
      "Religion": "58.9% Christianity",
      "Government": "Unitary Marxist–Leninist one-party socialist republic",
      "Legislature": "National Assembly of People's Power",
      "Gini": "38.0",
      "HDI": "0.764",
      "Currency": "Peso",
      "Time zone": "UTC−5",
      "Driving side": "right",
      "Calling code": "+53",
      "Name": "cuba"
    },
    {
      "Capital": "Prague",
      "Official language": "Czech",
      "Ethnic groups": "89% Czechs",
      "Religion": "56.9% no religion",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "24.2",
      "HDI": "0.889",
      "Currency": "Koruna",
      "Time zone": "UTC+1",
      "Date format": "d. m. yyyy",
      "Driving side": "right",
      "Calling code": "+420",
      "Name": "czech republic"
    },
    {
      "Capital": "Stockholm",
      "Official languages": "Swedish",
      "National minority languages": "SámiFinnishMeänkieliRomaniYiddish",
      "Religion": "61.4% Christianity",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Riksdag",
      "Gini": "27.6",
      "HDI": "0.947",
      "Currency": "Krona",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Name": "sweden"
    },
    {
      "Capital": "Santo Domingo",
      "Official languages": "Spanish",
      "Other spoken languages": "Haitian Creole",
      "Ethnic groups": "73.9% Mixed",
      "Religion": "66.7% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Congress",
      "Gini": "39.6",
      "HDI": "0.767",
      "Currency": "Peso",
      "Time zone": "UTC  – 4:00",
      "Driving side": "right",
      "Calling code": "+1-809, +1-829, +1-849",
      "Name": "dominican republic"
    },
    {
      "Capital": "Lisbon",
      "Official languages": "Portuguese",
      "Recognised regional languages": "Mirandese",
      "Nationality": "92.5% Portuguese nationals",
      "Religion": "85% Christianity",
      "Government": "Unitary semi-presidential constitutional republic",
      "Legislature": "Assembly of the Republic",
      "Gini": "31.2",
      "HDI": "0.866",
      "Currency": "Euro",
      "Time zone": "UTC",
      "Calling code": "+351",
      "Name": "portugal"
    },
    {
      "Capital": "Athens",
      "Official language": "Greek",
      "Religion": "93% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Hellenic Parliament",
      "Gini": "31.4",
      "HDI": "0.887",
      "Currency": "Euro",
      "Time zone": "UTC+02:00",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+30",
      "Name": "greece"
    },
    {
      "Capital": "Baku",
      "Official languages": "Azerbaijani",
      "Ethnic groups": "94.8% Azerbaijani",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "National Assembly",
      "Gini": "33.7",
      "HDI": "0.745",
      "Currency": "Manat",
      "Time zone": "UTC+4",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+994",
      "Name": "azerbaijan"
    },
    {
      "Capital": "Tegucigalpa",
      "Official languages": "Spanish",
      "Ethnic groups": "90% Mestizo",
      "Religion": "75.7% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Congress",
      "Gini": "52.1",
      "HDI": "0.621",
      "Currency": "Lempira",
      "Time zone": "UTC−6",
      "Driving side": "right",
      "Calling code": "+504",
      "Name": "honduras"
    },
    {
      "Capital": "Dushanbe",
      "Official languages": "Tajik",
      "Spoken languages": "Tajik Russian",
      "Ethnic groups": "84.3% Tajiks",
      "Religion": "96.4% Islam",
      "Government": "Unitary presidential republic under an authoritarian dictatorship",
      "Legislature": "Supreme Assembly",
      "Gini": "34",
      "HDI": "0.685",
      "Currency": "Somoni",
      "Time zone": "UTC+5",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+992",
      "Name": "tajikistan"
    },
    {
      "Capital": "Budapest",
      "Official languages": "Hungarian",
      "Ethnic groups": "87.9% Hungarians",
      "Religion": "42.5% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "National Assembly",
      "Gini": "28.3",
      "HDI": "0.846",
      "Currency": "Forint",
      "Time zone": "UTC+1",
      "Date format": "yyyy. mm. dd.",
      "Driving side": "right",
      "Calling code": "+36",
      "Seats": "199",
      "Political groups": "Government",
      "Name": "hungary"
    },
    {
      "Capital": "Minsk",
      "Official languages": "Belarusian Russiana",
      "Recognized minority languages": "Polish Ukrainian Yiddish",
      "Ethnic groups": "84.9% Belarusians",
      "Religion": "91.0% Christianity",
      "Government": "Unitary presidential republic under a dictatorship",
      "Legislature": "National Assembly",
      "Gini": "25.3",
      "HDI": "0.808",
      "Currency": "Ruble",
      "Time zone": "UTC+3",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+375",
      "Name": "belarus"
    },
    {
      "Capital": "Abu Dhabi",
      "Largest city": "Dubai",
      "Official languages": "Arabic",
      "Common languages": "Gulf Arabic, English",
      "Ethnic groups": "59.4% South Asian",
      "Religion": "76% Islam",
      "Government": "Federal Islamic semi-constitutional monarchy",
      "Legislature": "Federal Supreme Council",
      "Gini": "26.0",
      "HDI": "0.911",
      "Currency": "Dirham",
      "Time zone": "UTC+04:00",
      "Calling code": "+971",
      "Name": "united arab emirates"
    },
    {
      "Capital": "Vienna",
      "Official languages": "German",
      "National language": "Austrian German",
      "Official regional languages": "Hungarian",
      "Ethnic groups": "75.6% Austrians",
      "Religion": "64.1% Christianity",
      "Government": "Federal parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "26.7",
      "HDI": "0.916",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+43",
      "Name": "austria"
    },
    {
      "Capital": "Freetown",
      "Official languages": "English",
      "Recognised national languages": "Krio",
      "Ethnic groups": "35.5% Mende",
      "Government": "Unitary presidential republic",
      "Legislature": "Parliament",
      "Gini": "35.7",
      "HDI": "0.477",
      "Currency": "Leone",
      "Time zone": "UTC",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+232",
      "Name": "sierra leone"
    },
    {
      "Capital": "None",
      "Largest city": "Zürich",
      "Official languages": "German",
      "Religion": "62.6% Christianity",
      "Government": "Federal assembly-independent",
      "Legislature": "Federal Assembly",
      "Gini": "29.7",
      "HDI": "0.962",
      "Currency": "Franc",
      "Time zone": "UTC+1",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+41",
      "Name": "switzerland"
    },
    {
      "Capital": "Lomé",
      "Official languages": "French",
      "Religion": "47.8% Christianity",
      "Government": "Unitary presidential republic under an authoritarian dictatorship",
      "Legislature": "National Assembly",
      "Gini": "43.1",
      "HDI": "0.539",
      "Currency": "West African CFA franc",
      "Time zone": "UTC",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+228",
      "Name": "togo"
    },
    {
      "Capital": "Vientiane",
      "Official languages": "Lao",
      "Spoken languages": "Lao Khmu Hmong Phu Thai",
      "Ethnic groups": "53.2% Lao",
      "Religion": "66.0% Buddhism",
      "Government": "Unitary Marxist–Leninist one-party socialist republic",
      "Legislature": "National Assembly",
      "Gini": "36.4",
      "HDI": "0.607",
      "Currency": "Kip",
      "Time zone": "UTC+7",
      "Driving side": "right",
      "Calling code": "+856",
      "Name": "laos"
    },
    {
      "Capital": "Bishkek",
      "Official languages": "Kyrgyz",
      "Official script": "Cyrillic",
      "Spoken languages": "Kyrgyz",
      "Ethnic groups": "77.7% Kyrgyz",
      "Religion": "90% Islam",
      "Government": "Unitary presidential republic",
      "Legislature": "Supreme Council",
      "Gini": "29.0",
      "HDI": "0.692",
      "Currency": "Som",
      "Time zone": "UTC+6",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+996",
      "Name": "kyrgyzstan"
    },
    {
      "Capital": "Ashgabat",
      "Official languages": "Turkmen",
      "Ethnic groups": "85.6% Turkmens",
      "Religion": "93% Islam",
      "Government": "Unitary presidential republic under a totalitarian hereditary dictatorship",
      "Legislature": "Assembly",
      "Gini": "40.8",
      "HDI": "0.745",
      "Currency": "Manat",
      "Time zone": "UTC+05",
      "Driving side": "right",
      "Calling code": "+993",
      "Name": "turkmenistan"
    },
    {
      "Capital": "Tripoli",
      "Official languages": "Arabic",
      "Local vernacular": "Libyan Arabic",
      "Ethnic groups": "92% Arabs",
      "Religion": "99.7% Islam",
      "Government": "Unitary republic under a provisional unity government",
      "Legislature": "House of Representatives",
      "HDI": "0.718",
      "Currency": "Dinar",
      "Time zone": "UTC+2",
      "Driving side": "right",
      "Calling code": "+218",
      "Name": "libya"
    },
    {
      "Capital": "San Salvador",
      "Official languages": "Spanish",
      "Ethnic groups [1]": "86.3% Mestizo",
      "Religion": "84.1% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "Legislative Assembly",
      "Gini": "38.8",
      "HDI": "0.675",
      "Currency": "Dollar",
      "Time zone": "UTC−6",
      "Driving side": "right",
      "Calling code": "+503",
      "Name": "el salvador"
    },
    {
      "Capital": "Managua",
      "Official languages": "Spanish",
      "Recognised regional languages": "Miskito",
      "Ethnic groups": "69% Mestizo",
      "Religion": "84.4% Christianity",
      "Government": "Unitary presidential republic under an authoritarian dictatorship",
      "Legislature": "National Assembly",
      "Gini": "46.2",
      "HDI": "0.667",
      "Currency": "Córdoba",
      "Time zone": "UTC−6",
      "Driving side": "right",
      "Calling code": "+505",
      "Name": "nicaragua"
    },
    {
      "Capital": "Sofia",
      "Official languages": "Bulgarian",
      "Official script": "Cyrillic",
      "Ethnic groups": "84.6% Bulgarians",
      "Religion": "71.5% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "National Assembly",
      "Gini": "38.4",
      "HDI": "0.796",
      "Currency": "Lev",
      "Time zone": "UTC+2",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+359",
      "Name": "bulgaria"
    },
    {
      "Capital": "Belgrade",
      "Official languages": "Serbian",
      "Ethnic groups": "84.4% Serbs",
      "Religion": "86.6% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "National Assembly",
      "Gini": "33.3",
      "HDI": "0.802",
      "Currency": "Dinar",
      "Time zone": "UTC+1",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+381",
      "Name": "serbia"
    },
    {
      "Capital": "Asunción",
      "Official languages[1][2]": "SpanishGuarani",
      "Religion": "96.1% Christianity",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "Congress",
      "Gini": "43.5",
      "HDI": "0.717",
      "Currency": "Guaraní",
      "Time zone": "UTC–4",
      "Driving side": "right",
      "Calling code": "+595",
      "Name": "paraguay"
    },
    {
      "Capital": "Brazzaville",
      "Official languages": "French",
      "Recognised national languages": "Lingala Kituba",
      "Religion": "87.1% Christianity",
      "Government": "Unitary semi-presidential republic under a dominant-party authoritarian state",
      "Legislature": "Parliament",
      "Gini": "40.2",
      "HDI": "0.571",
      "Currency": "Central African CFA franc",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+242",
      "Name": "republic of the congo"
    },
    {
      "Tamil:": "சிங்கப்பூர் குடியரசு",
      "Capital": "Singapore",
      "Largest planning area by population": "Bedok",
      "Official languages": "English Malay Mandarin Tamil",
      "National language": "Malay",
      "Ethnic groups": "74.3% Chinese",
      "Religion": "31.1% Buddhism",
      "Government": "Unitary dominant-party parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "45.9",
      "HDI": "0.939",
      "Currency": "Dollar",
      "Time zone": "UTC+8",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+65",
      "Name": "singapore"
    },
    {
      "Sovereign state": "Kingdom of Denmark",
      "Consolidation": "c. 8th century",
      "Christianization": "c. 965",
      "Constitutional Act": "5 June 1849",
      "Faroese home rule": "24 March 1948",
      "EEC accession": "1 January 1973",
      "Greenlandic home rule": "1 May 1979",
      "Capital": "Copenhagen",
      "Official languages": "Danish",
      "Regional languages": "German",
      "Ethnic groups": "86.11% Danish",
      "Religion": "75.8% Christianity",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Folketing",
      "Highest elevation": "170.86 m",
      "Gini": "27.7",
      "HDI": "0.948",
      "Currency": "Krone",
      "Time zone": "UTC+01:00",
      "Date format": "dd/mm/yyyy",
      "Mains electricity": "230 V–50 Hz",
      "Driving side": "right",
      "Calling code": "+45",
      "Website": "denmark.dk",
      "Name": "denmark"
    },
    {
      "Capital": "Bangui",
      "Official languages": "Sango French",
      "Religion": "73.2% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "56.3",
      "HDI": "0.404",
      "Currency": "Central African CFA franc",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+236",
      "Name": "central african republic"
    },
    {
      "Capital": "Oslo",
      "Official languages": "Norwegian",
      "Recognised national languages": "Kven Romani Scandoromani",
      "Ethnic groups": "81.5% Norwegian",
      "Religion": "74.9% Christianity",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Storting",
      "Gini": "25.3",
      "HDI": "0.961",
      "Currency": "Krone",
      "Time zone": "UTC+1",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+47",
      "Name": "norway"
    },
    {
      "Capital": "Helsinki",
      "Official languages": "Finnish Swedish",
      "Recognized national languages": "Sami Karelian Finnish Kalo",
      "Ethnic groups": "91.5% Finns",
      "Religion": "68.6% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "26.6",
      "HDI": "0.940",
      "Currency": "Euro",
      "Time zone": "UTC+2",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+358",
      "Name": "finland"
    },
    {
      "Capital": "Beirut",
      "Official languages": "Arabic",
      "Local vernacular": "Lebanese Arabic",
      "Foreign languages": "French",
      "Ethnic groups": "95% Arab",
      "Government": "Unitary parliamentary republic that includes confessionalism",
      "Legislature": "Parliament",
      "Gini": "31.8",
      "HDI": "0.706",
      "Currency": "Pound",
      "Time zone": "UTC+2",
      "Driving side": "right",
      "Calling code": "+961",
      "Name": "lebanon"
    },
    {
      "Status": "UN observer state under Israeli occupation",
      "Proclaimed capital": "Jerusalem",
      "Largest city": "Gaza City",
      "Official languages": "Arabic",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "National Council",
      "Gini": "33.7",
      "HDI": "0.715",
      "Currency": "Pound",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+970",
      "Name": "palestine"
    },
    {
      "Capital": "Bratislava",
      "Official languages": "Slovak",
      "Ethnic groups": "83.8% Slovaks",
      "Religion": "68.8% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "National Council",
      "Gini": "21.2",
      "HDI": "0.848",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "d. m. yyyy",
      "Driving side": "right",
      "Calling code": "+421",
      "Name": "slovakia"
    },
    {
      "Capital": "Dublin",
      "Official languages": "Irish",
      "Ethnic groups": "76.6% White Irish",
      "Religion": "75.7% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Oireachtas",
      "Gini": "27.9",
      "HDI": "0.945",
      "Currency": "Euro",
      "Time zone": "UTC",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+353",
      "Name": "ireland"
    },
    {
      "Capital": "Monrovia",
      "Official languages": "English",
      "Ethnic groups": "20.3% Kpelle",
      "Religion": "85.1% Christianity",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "Legislature of Liberia",
      "Gini": "35.3",
      "HDI": "0.481",
      "Currency": "Dollar",
      "Time zone": "UTC",
      "Date format": "mm/dd/yyyy",
      "Driving side": "right",
      "Calling code": "+231",
      "Name": "liberia"
    },
    {
      "Capital": "San José",
      "Official languages": "Spanish",
      "Recognized regional languages": "Mekatelyu Bribri Patois",
      "Ethnic groups": "83.6% White or Mestizo",
      "Religion": "72.6% Christianity",
      "Government": "Unitary presidential constitutional republic",
      "Legislature": "Legislative Assembly",
      "Gini": "47.2",
      "HDI": "0.809",
      "Currency": "Colón",
      "Time zone": "UTC−6",
      "Driving side": "right",
      "Calling code": "+506",
      "Name": "costa rica"
    },
    {
      "Capital": "Kuwait City",
      "Official languages": "Arabic",
      "Other languages": "English",
      "Ethnic groups": "57.8% Arabs",
      "Religion": "76.7% Islam",
      "Government": "Unitary parliamentary constitutional elective monarchy",
      "Legislature": "National Assembly",
      "HDI": "0.831",
      "Currency": "Dinar",
      "Time zone": "UTC+3",
      "Name": "kuwait"
    },
    {
      "Capital": "Muscat",
      "Official languages": "Arabic",
      "Religion": "88.9% Islam",
      "Government": "Unitary Islamic absolute monarchy",
      "Legislature": "Council of Oman",
      "Gini": "30.75",
      "HDI": "0.816",
      "Currency": "Rial",
      "Time zone": "UTC+4",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+968",
      "Name": "oman"
    },
    {
      "Capital": "Wellington",
      "Largest city": "Auckland",
      "Official languages": "English",
      "Ethnic groups": "70.2% European",
      "Religion": "48.2% no religion",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Parliament",
      "Gini": "30.0",
      "HDI": "0.937",
      "Currency": "Dollar",
      "Time zone": "UTC+12",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+64",
      "Name": "new zealand"
    },
    {
      "Capital": "Nouakchott",
      "Official languages": "Arabic",
      "Recognised national languages": "Pulaar",
      "Ethnic groups": "40% Haratin",
      "Religion": "Sunni Islam",
      "Government": "Unitary presidential Islamic republic",
      "Legislature": "National Assembly",
      "Gini": "32.6",
      "HDI": "0.556",
      "Currency": "Ouguiya",
      "Time zone": "UTC",
      "Name": "mauritania"
    },
    {
      "Capital": "Zagreb",
      "Official languages": "Croatian",
      "Writing system": "Latin",
      "Ethnic groups": "91.6% Croats",
      "Religion": "87.4% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Sabor",
      "Gini": "28.3",
      "HDI": "0.858",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "dd. mm. yyyy.",
      "Driving side": "right",
      "Calling code": "+385",
      "Name": "croatia"
    },
    {
      "Capital": "Panama City",
      "Official languages": "Spanish",
      "Ethnic groups": "65.0% Mestizo",
      "Religion": "91.5% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "49.9",
      "HDI": "0.805",
      "Currency": "Balboa",
      "Time zone": "UTC−5",
      "Date format": "mm/dd/yyyy",
      "Driving side": "right",
      "Calling code": "+507",
      "Name": "panama"
    },
    {
      "Capital": "Asmara",
      "Official languages": "None",
      "Recognised national languages": "Tigrinya",
      "Working languages": "Tigrinya",
      "Ethnic groups": "50% Tigrinya",
      "Government": "Unitary one-party presidential republic under a totalitarian dictatorship",
      "Legislature": "National Assembly",
      "HDI": "0.459",
      "Currency": "Nakfa",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+291",
      "Name": "eritrea"
    },
    {
      "Capital": "Montevideo",
      "Official language": "Spanish",
      "Ethnic groups": "87.7% White",
      "Religion": "54.3% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "General Assembly",
      "Gini": "40.8",
      "HDI": "0.809",
      "Currency": "Peso",
      "Time zone": "UTC−3",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+598",
      "Name": "uruguay"
    },
    {
      "Capital": "Sarajevo",
      "Official languages": "None",
      "Writing system": "LatinCyrillic",
      "Ethnic groups": "50.1% Bosniaks",
      "Religion": "51% Islam",
      "Government": "Federal parliamentary",
      "Legislature": "Parliamentary Assembly",
      "Gini": "32.7",
      "HDI": "0.780",
      "Currency": "Mark",
      "Time zone": "UTC+01",
      "Date format": "d. m. yyyy.",
      "Driving side": "right",
      "Calling code": "+387",
      "Name": "bosnia and herzegovina"
    },
    {
      "Capital": "Kingston",
      "Official languages": "English",
      "National language": "Jamaican Patois",
      "Ethnic groups": "92.1% Afro-Jamaicans",
      "Religion": "68.9% Christianity",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Parliament",
      "Gini": "35",
      "HDI": "0.734",
      "Currency": "Ddollar",
      "Time zone": "UTC-5",
      "Driving side": "left",
      "Calling code": "+1-876",
      "Name": "jamaica"
    },
    {
      "Capital": "Ulaanbaatar",
      "Official languages": "Mongolian",
      "Official scripts": "Mongolian Cyrillic",
      "Ethnic groups": "95% Mongols",
      "Religion": "51.7% Buddhism",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "State Great Khural",
      "Gini": "32.7",
      "HDI": "0.739",
      "Currency": "Tögrög",
      "Time zone": "UTC+7/+8",
      "Date format": "yyyy.mm.dd",
      "Driving side": "right",
      "Calling code": "+976",
      "Mongolian Cyrillic": "Монгол Улс",
      "Mongolian script": "ᠮᠣᠩᠭᠣᠯ",
      "SASM/GNC": "Mongol Uls",
      "Name": "mongolia"
    },
    {
      "Capital": "Yerevan",
      "Official languages": "Armenian",
      "Ethnic groups": "98.1% Armenians",
      "Religion": "Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "National Assembly",
      "Gini": "29.9",
      "HDI": "0.759",
      "Currency": "Dram",
      "Time zone": "UTC+4",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+374",
      "Name": "armenia"
    },
    {
      "Capital": "Tirana",
      "Official languages": "Albanian",
      "Recognised minority languages": "Greek Aromanian Macedonian",
      "Religion": "59% Islam",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Kuvendi",
      "Gini": "34.3",
      "HDI": "0.796",
      "Currency": "Lek",
      "Time zone": "UTC+1",
      "Driving side": "right",
      "Calling code": "+355",
      "Name": "albania"
    },
    {
      "Capital": "Doha",
      "Official languages": "Arabic",
      "Common languages": "English",
      "Ethnic groups": "40% Arab",
      "Religion": "65.5% Islam",
      "Government": "Unitary authoritarian",
      "Legislature": "Consultative Assembly",
      "Gini": "41.1",
      "HDI": "0.855",
      "Currency": "Riyal",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+974",
      "Name": "qatar"
    },
    {
      "Capital": "Vilnius",
      "Official languages": "Lithuanian",
      "Ethnic groups": "83.6% Lithuanians",
      "Religion": "79.4% Christianity",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Seimas",
      "Gini": "36.2",
      "HDI": "0.875",
      "Currency": "Euro",
      "Time zone": "UTC+2",
      "Date format": "yyyy-mm-dd",
      "Driving side": "right",
      "Calling code": "+370",
      "Name": "lithuania"
    },
    {
      "Afrikaans:": "Republiek van Namibië",
      "German:": "Republik Namibia",
      "Khoekhoegowab:": "Republiki Namibiab dib",
      "Otjiherero:": "Orepublika yaNamibia",
      "Oshiwambo:": "Orepublika yaNamibia",
      "RuKwangali:": "Republika zaNamibia",
      "Setswana:": "Rephaboliki ya Namibia",
      "siLozi:": "Namibia ye Lukuluhile",
      "Capital": "Windhoek",
      "Official languages": "English",
      "Recognised national languages": "Afrikaans",
      "Recognised regional languages": "!Kung",
      "Ethnic groups": "49% Ovambo",
      "Religion": "87.9% Christianity",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "Parliament",
      "Gini": "59.1",
      "HDI": "0.615",
      "Currency": "Dollar",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+264",
      "Name": "namibia"
    },
    {
      "Capital": "Banjul",
      "Largest metropolitan area": "Serekunda",
      "Official languages": "English",
      "Ethnic groups": "34.4% Mandinka",
      "Religion": "96.4% Islam",
      "Government": "Unitary presidential republic",
      "Legislature": "National Assembly",
      "Gini": "35.9",
      "HDI": "0.500",
      "Currency": "Dalasi",
      "Time zone": "UTC",
      "Driving side": "right",
      "Calling code": "+220",
      "Name": "the gambia"
    },
    {
      "Capital": "Gaborone",
      "Official languages": "English",
      "National language": "Setswana",
      "Ethnic groups": "79% Tswana",
      "Religion": "79.1% Christianity",
      "Government": "Unitary dominant-party parliamentary republic with an executive presidency",
      "Legislature": "Parliament",
      "Gini": "53.3",
      "HDI": "0.693",
      "Currency": "Pula",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+267",
      "Person": "Motswana",
      "People": "Batswana",
      "Language": "Setswana",
      "Country": "Botswana",
      "Name": "botswana"
    },
    {
      "Name": "lesotho"
    },
    {
      "Capital": "Skopje",
      "Official languages": "Macedonian",
      "Official regional languages": "Turkish",
      "Ethnic groups": "58.4% Macedonians",
      "Religion": "60.4% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Assembly",
      "Gini": "30.7",
      "HDI": "0.770",
      "Currency": "Denar",
      "Time zone": "UTC+1",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+389",
      "Name": "north macedonia"
    },
    {
      "Capital": "Libreville",
      "Official languages": "French",
      "Religion": "75.6% Christianity",
      "Government": "Unitary presidential republic under a military junta",
      "Legislature": "Parliament of Gabon",
      "Gini": "38",
      "HDI": "0.706",
      "Currency": "Central African CFA franc",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+241",
      "Name": "gabon"
    },
    {
      "Capital": "Ljubljana",
      "Official languages": "Slovene",
      "Recognised regional languages": "ItalianHungarian",
      "Ethnic groups": "83.1% Slovenes",
      "Religion": "77.8% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "23.5",
      "HDI": "0.918",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "dd. mm. yyyy",
      "Driving side": "right",
      "Calling code": "+386",
      "Name": "slovenia"
    },
    {
      "Capital": "Bissau",
      "Official languages": "Portuguese",
      "Ethnic groups": "30% Balanta",
      "Religion": "46.1% Islam",
      "Government": "Unitary semi-presidential republic",
      "Legislature": "National People's Assembly",
      "Gini": "50.7",
      "HDI": "0.483",
      "Currency": "West African CFA franc",
      "Time zone": "UTC",
      "Driving side": "right",
      "Calling code": "+245",
      "Name": "guinea-bissau"
    },
    {
      "Capital": "Riga",
      "Official languages": "Latviana",
      "Recognized languages": "Livonian",
      "Ethnic groups": "63.0% Latvians",
      "Religion": "64% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Saeima",
      "Gini": "35.7",
      "HDI": "0.863",
      "Currency": "Euro",
      "Time zone": "UTC+2",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+371",
      "Name": "latvia"
    },
    {
      "Capital": "Manama",
      "Official languages": "Arabic",
      "Ethnic groups": "53.2% Arabs",
      "Religion": "80.6% Islam",
      "Government": "Unitary Islamic parliamentary semi-constitutional monarchy",
      "Legislature": "National Assembly",
      "HDI": "0.875",
      "Currency": "Dinar",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+973",
      "Name": "bahrain"
    },
    {
      "Capital": "Port of Spain",
      "Largest city": "San Fernando",
      "Official languages": "English",
      "Ethnic groups": "35.43% Indian",
      "Religion": "63.2% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "39.0",
      "HDI": "0.810",
      "Currency": "Dollar",
      "Time zone": "UTC-4",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+1",
      "Name": "trinidad and tobago"
    },
    {
      "Capital": "Malabo",
      "Official languages": "Spanish",
      "Ethnic groups": "85.7% Fang",
      "Religion": "88.7% Christianity",
      "Government": "Unitary dominant-party presidential republic under a dictatorship",
      "Legislature": "Parliament",
      "HDI": "0.596",
      "Currency": "Central African CFA franc",
      "Time zone": "UTC+1",
      "Date format": "dd/mm/yyyy",
      "Driving side": "right",
      "Calling code": "+240",
      "Name": "equatorial guinea"
    },
    {
      "Capital": "Tallinn",
      "Official language": "Estonian",
      "Religion": "58.4% no religion",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Riigikogu",
      "Gini": "30.6",
      "HDI": "0.890",
      "Currency": "Euro",
      "Time zone": "UTC+02:00",
      "Driving side": "right",
      "Calling code": "+372",
      "Name": "estonia"
    },
    {
      "Capital": "Nicosia",
      "Official languages": "Greek",
      "Minority languages": "Armenian",
      "Vernaculars": "Cypriot Greek",
      "Ethnic groups": "Greek Cypriots",
      "Religion": "72.3% Christianity",
      "Government": "Unitary presidential republic",
      "Legislature": "House of Representatives",
      "Gini": "29.4",
      "HDI": "0.896",
      "Currency": "Euro",
      "Time zone": "UTC+02:00",
      "Driving side": "left",
      "Calling code": "+357",
      "Name": "cyprus"
    },
    {
      "Capital": "Luxembourg City",
      "Official languages": "National language:",
      "Nationality": "52.8% Luxembourgers",
      "Religion": "73.2% Christianity",
      "Government": "Unitary parliamentary constitutional monarchy",
      "Legislature": "Chamber of Deputies",
      "Gini": "32.3",
      "HDI": "0.930",
      "Currency": "Euro",
      "Time zone": "UTC+1",
      "Date format": "dd.mm.yyyy",
      "Driving side": "right",
      "Calling code": "+352",
      "Name": "luxembourg"
    },
    {
      "Capital": "Port Louis",
      "Official languages": "None",
      "Lingua franca": "Mauritian Creole",
      "Language Spoken at Home": "90.0% Mauritian Creole",
      "Ethnic groups": "67% Indian",
      "Religion": "48.54% Hinduism",
      "Government": "Unitary parliamentary republic",
      "Legislature": "National Assembly",
      "Gini": "36.8",
      "HDI": "0.802",
      "Currency": "Rupee",
      "Time zone": "UTC+4",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+230",
      "Name": "mauritius"
    },
    {
      "Capital": "Mbabane",
      "Largest city": "Mbabane",
      "Official languages": "Swazi English",
      "Ethnic groups": "84% Swazi",
      "Religion": "89.3% Christianity",
      "Government": "Unitary absolute monarchy",
      "Legislature": "Parliament",
      "Gini": "54.6",
      "HDI": "0.597",
      "Currency": "Lilangeni",
      "Time zone": "UTC+2",
      "Driving side": "left",
      "Calling code": "+268",
      "Person": "liSwati",
      "People": "emaSwati",
      "Language": "siSwati",
      "Country": "eSwatini",
      "Name": "eswatini"
    },
    {
      "Capital": "Suva",
      "Official languages": "iTaukei",
      "Recognised regional languages": "Rotuman",
      "Ethnic groups": "56.8% Indigenous Fijians",
      "Religion": "64.4% Christianity",
      "Government": "Unitary parliamentary republic",
      "Legislature": "Parliament",
      "Gini": "36.4",
      "HDI": "0.730",
      "Currency": "Dollar",
      "Time zone": "UTC+12",
      "Date format": "dd/mm/yyyy",
      "Driving side": "left",
      "Calling code": "+679",
      "Name": "fiji"
    },
    {
      "Capital": "Djibouti",
      "Official languages": "Arabic French",
      "National languages": "SomaliA far",
      "Ethnic groups": "Somalis 60%",
      "Religion": "94% Islam",
      "Government": "Unitary presidential republic under a dictatorship",
      "Legislature": "National Assembly",
      "Gini": "41.6",
      "HDI": "0.509",
      "Currency": "Franc",
      "Time zone": "UTC+3",
      "Driving side": "right",
      "Calling code": "+253",
      "Name": "djibouti"
    }
  ]